# NumPy Basics

NumPy is one of the most important libraries in Python used for numerical computing and data science.

-----
## What is NumPy?

NumPy stands for **Numerical Python**.

It is a Python library used for working with:
- arrays
- matrices
- mathematical operations
- large datasets
----

## History of NumPy

NumPy was created in 2005 by Travis Oliphant.

It was built by combining:
- Numeric (older library)
- Numarray

NumPy became the standard library for numerical computing in Python.

---

## Why NumPy was created?

Before NumPy:
- Python lists were used for numbers
- They were slow for large data
- No mathematical operations directly

NumPy was created to solve these problems:
- Faster computation
- Less memory usage
- Easy mathematical operations

-----
## Why NumPy is better than Python lists?

Python list:
- slow for large data
- no built-in math operations

NumPy array:
- faster
- uses less memory
- supports vector operations
-----
## NumPy Array (Main Concept)

The most important feature of NumPy is the **array**.

NumPy array is similar to a list but:
- faster
- more powerful
- supports mathematical operations

In [1]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])
print(arr)

[1 2 3 4 5]


----
## Types of NumPy Arrays

1D Array → single row  
2D Array → rows and columns (matrix)  
3D Array → collection of matrices

----
## Creating NumPy Arrays

We can create arrays using:
- np.array()
- np.arange()
- np.zeros()
- np.ones()
- random functions

---

## np.array()

np.array() is used to create a NumPy array from a Python list.

----

In [4]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])
print(arr)

[1 2 3 4 5]


----
## np.arange()

np.arange() is used to create arrays with a range of values.

Syntax:
np.arange(start, stop, step)

---

In [2]:
import numpy as np

print(np.arange(1, 10))

[1 2 3 4 5 6 7 8 9]


In [3]:
print(np.arange(1, 10, 2))

[1 3 5 7 9]


----
## np.zeros()

np.zeros() creates an array filled with 0s.

---

In [5]:
print(np.zeros(5))

[0. 0. 0. 0. 0.]


-----
## np.ones()

np.ones() creates an array filled with 1s.

---

In [6]:
print(np.ones(5))

[1. 1. 1. 1. 1.]


----
## Random Functions in NumPy

NumPy provides random functions to generate random numbers.

### np.random.rand()

Generates random numbers between 0 and 1.

---

In [7]:
print(np.random.rand(5))

[0.48469189 0.18634409 0.91641775 0.84035741 0.00724095]


----
### np.random.randint()

Generates random integers between a given range.

----

In [8]:
print(np.random.randint(1, 10, 5))

[2 1 3 5 5]


----
## Random Functions in NumPy (Important Concept)

NumPy random functions work differently:

### np.random.rand()
- Generates random numbers between 0 and 1
- Output is float values
- You only control number of outputs

### np.random.randint()
- Generates random integers
- You can control:
  - start range
  - end range
  - number of values

### Key Difference:
- rand() → fixed range (0 to 1)
- randint() → custom range defined by user
----

## Indexing in NumPy Arrays

Indexing is used to access individual elements from a NumPy array.

Positive indexing starts from 0.

Negative indexing starts from -1.

-----

In [1]:
import numpy as np

arr = np.array([10, 20, 30, 40, 50])

# accessing first element
print(arr[0])

# accessing third element
print(arr[2])

# accessing last element
print(arr[-1])

10
30
50


-----
## Slicing in NumPy Arrays

Slicing is used to access multiple elements from an array.

Syntax:
array[start : stop : step]

Important:
- stop index is excluded
----

In [2]:
arr = np.array([10, 20, 30, 40, 50])

# slicing elements from index 1 to 3
print(arr[1:4])

[20 30 40]


In [3]:
# elements from beginning to index 2
print(arr[:3])

[10 20 30]


In [4]:
# elements from index 2 till end
print(arr[2:])

[30 40 50]


In [5]:
# slicing with step
print(arr[::2])

[10 30 50]


----
## Important Difference

Indexing → returns single element

Slicing → returns multiple elements

----

# #PRACTICE QUESTIONS
---


In [14]:
# Create a NumPy array from the list [10, 20, 30, 40, 50]

import numpy as np

arr = np.array([10, 20, 30, 40, 50])

print(arr)

[10 20 30 40 50]


In [16]:
# Create an array of 5 zeros using NumPy

import numpy as np

# creating array of 5 zeros
arr = np.zeros(5)

# printing result
print(arr)

[0. 0. 0. 0. 0.]


In [19]:
# Create an array of 6 ones using NumPy

import numpy as np

# creating array of 6 ones
arr = np.ones(6)

# printing result
print(arr)

[1. 1. 1. 1. 1. 1.]


In [24]:
# Generate 5 random numbers between 0 and 1

import numpy as np

# generating 5 random numbers between 0 and 1
arr = np.random.rand(5)

# printing result
print(arr)

[0.93424214 0.14673808 0.86930847 0.78951385 0.85595019]


In [27]:
# Generate 5 random integers between 1 and 20

import numpy as np

# generating 5 random integers between 1 and 20
arr = np.random.randint(1, 20, 5)

# printing result
print(arr)

[ 7 16  2 18 13]


In [35]:
# Create a NumPy array and print the first element

import numpy as np

# creating NumPy array
arr = np.array([5, 10, 15, 20, 25])

# printing first element
print(arr[0])


5


In [38]:
# Create a NumPy array and print the last element

import numpy as np

# creating NumPy array
arr = np.array([100, 200, 300, 400, 500])

# printing last element
print(arr[-1])

500


In [40]:
# Create a NumPy array and print elements from index 1 to 3

import numpy as np

# creating NumPy array
arr = np.array([2, 4, 6, 8, 10])

# slicing from index 1 to 3 (3 is excluded)
print(arr[1:3])

[4 6]


In [44]:
# Create an array of 10 zeros and convert it into ones

import numpy as np

# creating array of 10 zeros
arr = np.zeros(10)

# converting all elements to ones
arr = np.ones(10)

# printing result
print(arr)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


In [46]:
# Generate a random integer array of size 10 between 50 and 100

import numpy as np

# generating random integers between 50 and 100
arr = np.random.randint(50, 100, 10)

# printing result
print(arr)

[68 51 54 88 58 96 56 92 79 80]
